include "**/*.dart"

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_return: error
    dead_code: error

linter:
  rules:
    - always_declare_return_types
    - prefer_const_constructors
    - avoid_print
    - prefer_single_quotes
