/**
 *
 *  Sessions.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Sessions.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::backend;

const std::string Sessions::Cols::_id = "id";
const std::string Sessions::Cols::_verifier = "verifier";
const std::string Sessions::Cols::_code_challenge = "code_challenge";
const std::string Sessions::Cols::_code_challenge_method = "code_challenge_method";
const std::string Sessions::Cols::_created_at = "created_at";
const std::string Sessions::Cols::_access_token = "access_token";
const std::string Sessions::Cols::_expires_in = "expires_in";
const std::string Sessions::Cols::_refresh_expires_in = "refresh_expires_in";
const std::string Sessions::Cols::_refresh_token = "refresh_token";
const std::string Sessions::Cols::_token_type = "token_type";
const std::string Sessions::Cols::_not_before_policy = "not_before_policy";
const std::string Sessions::Cols::_session_state = "session_state";
const std::string Sessions::Cols::_scope = "scope";
const std::string Sessions::Cols::_expires_at = "expires_at";
const std::string Sessions::primaryKeyName = "id";
const bool Sessions::hasPrimaryKey = true;
const std::string Sessions::tableName = "sessions";

const std::vector<typename Sessions::MetaData> Sessions::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"verifier","std::string","character varying",128,0,0,1},
{"code_challenge","std::string","character varying",128,0,0,1},
{"code_challenge_method","std::string","character varying",32,0,0,1},
{"created_at","::trantor::Date","timestamp without time zone",0,0,0,1},
{"access_token","std::string","text",0,0,0,0},
{"expires_in","int32_t","integer",4,0,0,0},
{"refresh_expires_in","int32_t","integer",4,0,0,0},
{"refresh_token","std::string","text",0,0,0,0},
{"token_type","std::string","character varying",32,0,0,0},
{"not_before_policy","int32_t","integer",4,0,0,0},
{"session_state","std::string","character varying",128,0,0,0},
{"scope","std::string","text",0,0,0,0},
{"expires_at","::trantor::Date","timestamp without time zone",0,0,0,0}
};
const std::string &Sessions::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Sessions::Sessions(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["verifier"].isNull())
        {
            verifier_=std::make_shared<std::string>(r["verifier"].as<std::string>());
        }
        if(!r["code_challenge"].isNull())
        {
            codeChallenge_=std::make_shared<std::string>(r["code_challenge"].as<std::string>());
        }
        if(!r["code_challenge_method"].isNull())
        {
            codeChallengeMethod_=std::make_shared<std::string>(r["code_challenge_method"].as<std::string>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["access_token"].isNull())
        {
            accessToken_=std::make_shared<std::string>(r["access_token"].as<std::string>());
        }
        if(!r["expires_in"].isNull())
        {
            expiresIn_=std::make_shared<int32_t>(r["expires_in"].as<int32_t>());
        }
        if(!r["refresh_expires_in"].isNull())
        {
            refreshExpiresIn_=std::make_shared<int32_t>(r["refresh_expires_in"].as<int32_t>());
        }
        if(!r["refresh_token"].isNull())
        {
            refreshToken_=std::make_shared<std::string>(r["refresh_token"].as<std::string>());
        }
        if(!r["token_type"].isNull())
        {
            tokenType_=std::make_shared<std::string>(r["token_type"].as<std::string>());
        }
        if(!r["not_before_policy"].isNull())
        {
            notBeforePolicy_=std::make_shared<int32_t>(r["not_before_policy"].as<int32_t>());
        }
        if(!r["session_state"].isNull())
        {
            sessionState_=std::make_shared<std::string>(r["session_state"].as<std::string>());
        }
        if(!r["scope"].isNull())
        {
            scope_=std::make_shared<std::string>(r["scope"].as<std::string>());
        }
        if(!r["expires_at"].isNull())
        {
            auto timeStr = r["expires_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 14 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            verifier_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            codeChallenge_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            codeChallengeMethod_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            accessToken_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            expiresIn_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            refreshExpiresIn_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            refreshToken_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            tokenType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            notBeforePolicy_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            sessionState_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            scope_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

Sessions::Sessions(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 14)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            verifier_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            codeChallenge_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            codeChallengeMethod_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            accessToken_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            expiresIn_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            refreshExpiresIn_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            refreshToken_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            tokenType_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            notBeforePolicy_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            sessionState_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            scope_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[13]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

Sessions::Sessions(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("verifier"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["verifier"].isNull())
        {
            verifier_=std::make_shared<std::string>(pJson["verifier"].asString());
        }
    }
    if(pJson.isMember("code_challenge"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["code_challenge"].isNull())
        {
            codeChallenge_=std::make_shared<std::string>(pJson["code_challenge"].asString());
        }
    }
    if(pJson.isMember("code_challenge_method"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["code_challenge_method"].isNull())
        {
            codeChallengeMethod_=std::make_shared<std::string>(pJson["code_challenge_method"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("access_token"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["access_token"].isNull())
        {
            accessToken_=std::make_shared<std::string>(pJson["access_token"].asString());
        }
    }
    if(pJson.isMember("expires_in"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["expires_in"].isNull())
        {
            expiresIn_=std::make_shared<int32_t>((int32_t)pJson["expires_in"].asInt64());
        }
    }
    if(pJson.isMember("refresh_expires_in"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["refresh_expires_in"].isNull())
        {
            refreshExpiresIn_=std::make_shared<int32_t>((int32_t)pJson["refresh_expires_in"].asInt64());
        }
    }
    if(pJson.isMember("refresh_token"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["refresh_token"].isNull())
        {
            refreshToken_=std::make_shared<std::string>(pJson["refresh_token"].asString());
        }
    }
    if(pJson.isMember("token_type"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["token_type"].isNull())
        {
            tokenType_=std::make_shared<std::string>(pJson["token_type"].asString());
        }
    }
    if(pJson.isMember("not_before_policy"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["not_before_policy"].isNull())
        {
            notBeforePolicy_=std::make_shared<int32_t>((int32_t)pJson["not_before_policy"].asInt64());
        }
    }
    if(pJson.isMember("session_state"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["session_state"].isNull())
        {
            sessionState_=std::make_shared<std::string>(pJson["session_state"].asString());
        }
    }
    if(pJson.isMember("scope"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["scope"].isNull())
        {
            scope_=std::make_shared<std::string>(pJson["scope"].asString());
        }
    }
    if(pJson.isMember("expires_at"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["expires_at"].isNull())
        {
            auto timeStr = pJson["expires_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Sessions::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 14)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            verifier_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            codeChallenge_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            codeChallengeMethod_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            accessToken_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            expiresIn_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            refreshExpiresIn_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            refreshToken_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            tokenType_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            notBeforePolicy_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            sessionState_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            scope_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[13]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Sessions::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("verifier"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["verifier"].isNull())
        {
            verifier_=std::make_shared<std::string>(pJson["verifier"].asString());
        }
    }
    if(pJson.isMember("code_challenge"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["code_challenge"].isNull())
        {
            codeChallenge_=std::make_shared<std::string>(pJson["code_challenge"].asString());
        }
    }
    if(pJson.isMember("code_challenge_method"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["code_challenge_method"].isNull())
        {
            codeChallengeMethod_=std::make_shared<std::string>(pJson["code_challenge_method"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("access_token"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["access_token"].isNull())
        {
            accessToken_=std::make_shared<std::string>(pJson["access_token"].asString());
        }
    }
    if(pJson.isMember("expires_in"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["expires_in"].isNull())
        {
            expiresIn_=std::make_shared<int32_t>((int32_t)pJson["expires_in"].asInt64());
        }
    }
    if(pJson.isMember("refresh_expires_in"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["refresh_expires_in"].isNull())
        {
            refreshExpiresIn_=std::make_shared<int32_t>((int32_t)pJson["refresh_expires_in"].asInt64());
        }
    }
    if(pJson.isMember("refresh_token"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["refresh_token"].isNull())
        {
            refreshToken_=std::make_shared<std::string>(pJson["refresh_token"].asString());
        }
    }
    if(pJson.isMember("token_type"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["token_type"].isNull())
        {
            tokenType_=std::make_shared<std::string>(pJson["token_type"].asString());
        }
    }
    if(pJson.isMember("not_before_policy"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["not_before_policy"].isNull())
        {
            notBeforePolicy_=std::make_shared<int32_t>((int32_t)pJson["not_before_policy"].asInt64());
        }
    }
    if(pJson.isMember("session_state"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["session_state"].isNull())
        {
            sessionState_=std::make_shared<std::string>(pJson["session_state"].asString());
        }
    }
    if(pJson.isMember("scope"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["scope"].isNull())
        {
            scope_=std::make_shared<std::string>(pJson["scope"].asString());
        }
    }
    if(pJson.isMember("expires_at"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["expires_at"].isNull())
        {
            auto timeStr = pJson["expires_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &Sessions::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Sessions::getId() const noexcept
{
    return id_;
}
void Sessions::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void Sessions::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename Sessions::PrimaryKeyType & Sessions::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Sessions::getValueOfVerifier() const noexcept
{
    static const std::string defaultValue = std::string();
    if(verifier_)
        return *verifier_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Sessions::getVerifier() const noexcept
{
    return verifier_;
}
void Sessions::setVerifier(const std::string &pVerifier) noexcept
{
    verifier_ = std::make_shared<std::string>(pVerifier);
    dirtyFlag_[1] = true;
}
void Sessions::setVerifier(std::string &&pVerifier) noexcept
{
    verifier_ = std::make_shared<std::string>(std::move(pVerifier));
    dirtyFlag_[1] = true;
}

const std::string &Sessions::getValueOfCodeChallenge() const noexcept
{
    static const std::string defaultValue = std::string();
    if(codeChallenge_)
        return *codeChallenge_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Sessions::getCodeChallenge() const noexcept
{
    return codeChallenge_;
}
void Sessions::setCodeChallenge(const std::string &pCodeChallenge) noexcept
{
    codeChallenge_ = std::make_shared<std::string>(pCodeChallenge);
    dirtyFlag_[2] = true;
}
void Sessions::setCodeChallenge(std::string &&pCodeChallenge) noexcept
{
    codeChallenge_ = std::make_shared<std::string>(std::move(pCodeChallenge));
    dirtyFlag_[2] = true;
}

const std::string &Sessions::getValueOfCodeChallengeMethod() const noexcept
{
    static const std::string defaultValue = std::string();
    if(codeChallengeMethod_)
        return *codeChallengeMethod_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Sessions::getCodeChallengeMethod() const noexcept
{
    return codeChallengeMethod_;
}
void Sessions::setCodeChallengeMethod(const std::string &pCodeChallengeMethod) noexcept
{
    codeChallengeMethod_ = std::make_shared<std::string>(pCodeChallengeMethod);
    dirtyFlag_[3] = true;
}
void Sessions::setCodeChallengeMethod(std::string &&pCodeChallengeMethod) noexcept
{
    codeChallengeMethod_ = std::make_shared<std::string>(std::move(pCodeChallengeMethod));
    dirtyFlag_[3] = true;
}

const ::trantor::Date &Sessions::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Sessions::getCreatedAt() const noexcept
{
    return createdAt_;
}
void Sessions::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[4] = true;
}

const std::string &Sessions::getValueOfAccessToken() const noexcept
{
    static const std::string defaultValue = std::string();
    if(accessToken_)
        return *accessToken_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Sessions::getAccessToken() const noexcept
{
    return accessToken_;
}
void Sessions::setAccessToken(const std::string &pAccessToken) noexcept
{
    accessToken_ = std::make_shared<std::string>(pAccessToken);
    dirtyFlag_[5] = true;
}
void Sessions::setAccessToken(std::string &&pAccessToken) noexcept
{
    accessToken_ = std::make_shared<std::string>(std::move(pAccessToken));
    dirtyFlag_[5] = true;
}
void Sessions::setAccessTokenToNull() noexcept
{
    accessToken_.reset();
    dirtyFlag_[5] = true;
}

const int32_t &Sessions::getValueOfExpiresIn() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(expiresIn_)
        return *expiresIn_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Sessions::getExpiresIn() const noexcept
{
    return expiresIn_;
}
void Sessions::setExpiresIn(const int32_t &pExpiresIn) noexcept
{
    expiresIn_ = std::make_shared<int32_t>(pExpiresIn);
    dirtyFlag_[6] = true;
}
void Sessions::setExpiresInToNull() noexcept
{
    expiresIn_.reset();
    dirtyFlag_[6] = true;
}

const int32_t &Sessions::getValueOfRefreshExpiresIn() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(refreshExpiresIn_)
        return *refreshExpiresIn_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Sessions::getRefreshExpiresIn() const noexcept
{
    return refreshExpiresIn_;
}
void Sessions::setRefreshExpiresIn(const int32_t &pRefreshExpiresIn) noexcept
{
    refreshExpiresIn_ = std::make_shared<int32_t>(pRefreshExpiresIn);
    dirtyFlag_[7] = true;
}
void Sessions::setRefreshExpiresInToNull() noexcept
{
    refreshExpiresIn_.reset();
    dirtyFlag_[7] = true;
}

const std::string &Sessions::getValueOfRefreshToken() const noexcept
{
    static const std::string defaultValue = std::string();
    if(refreshToken_)
        return *refreshToken_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Sessions::getRefreshToken() const noexcept
{
    return refreshToken_;
}
void Sessions::setRefreshToken(const std::string &pRefreshToken) noexcept
{
    refreshToken_ = std::make_shared<std::string>(pRefreshToken);
    dirtyFlag_[8] = true;
}
void Sessions::setRefreshToken(std::string &&pRefreshToken) noexcept
{
    refreshToken_ = std::make_shared<std::string>(std::move(pRefreshToken));
    dirtyFlag_[8] = true;
}
void Sessions::setRefreshTokenToNull() noexcept
{
    refreshToken_.reset();
    dirtyFlag_[8] = true;
}

const std::string &Sessions::getValueOfTokenType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(tokenType_)
        return *tokenType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Sessions::getTokenType() const noexcept
{
    return tokenType_;
}
void Sessions::setTokenType(const std::string &pTokenType) noexcept
{
    tokenType_ = std::make_shared<std::string>(pTokenType);
    dirtyFlag_[9] = true;
}
void Sessions::setTokenType(std::string &&pTokenType) noexcept
{
    tokenType_ = std::make_shared<std::string>(std::move(pTokenType));
    dirtyFlag_[9] = true;
}
void Sessions::setTokenTypeToNull() noexcept
{
    tokenType_.reset();
    dirtyFlag_[9] = true;
}

const int32_t &Sessions::getValueOfNotBeforePolicy() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(notBeforePolicy_)
        return *notBeforePolicy_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Sessions::getNotBeforePolicy() const noexcept
{
    return notBeforePolicy_;
}
void Sessions::setNotBeforePolicy(const int32_t &pNotBeforePolicy) noexcept
{
    notBeforePolicy_ = std::make_shared<int32_t>(pNotBeforePolicy);
    dirtyFlag_[10] = true;
}
void Sessions::setNotBeforePolicyToNull() noexcept
{
    notBeforePolicy_.reset();
    dirtyFlag_[10] = true;
}

const std::string &Sessions::getValueOfSessionState() const noexcept
{
    static const std::string defaultValue = std::string();
    if(sessionState_)
        return *sessionState_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Sessions::getSessionState() const noexcept
{
    return sessionState_;
}
void Sessions::setSessionState(const std::string &pSessionState) noexcept
{
    sessionState_ = std::make_shared<std::string>(pSessionState);
    dirtyFlag_[11] = true;
}
void Sessions::setSessionState(std::string &&pSessionState) noexcept
{
    sessionState_ = std::make_shared<std::string>(std::move(pSessionState));
    dirtyFlag_[11] = true;
}
void Sessions::setSessionStateToNull() noexcept
{
    sessionState_.reset();
    dirtyFlag_[11] = true;
}

const std::string &Sessions::getValueOfScope() const noexcept
{
    static const std::string defaultValue = std::string();
    if(scope_)
        return *scope_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Sessions::getScope() const noexcept
{
    return scope_;
}
void Sessions::setScope(const std::string &pScope) noexcept
{
    scope_ = std::make_shared<std::string>(pScope);
    dirtyFlag_[12] = true;
}
void Sessions::setScope(std::string &&pScope) noexcept
{
    scope_ = std::make_shared<std::string>(std::move(pScope));
    dirtyFlag_[12] = true;
}
void Sessions::setScopeToNull() noexcept
{
    scope_.reset();
    dirtyFlag_[12] = true;
}

const ::trantor::Date &Sessions::getValueOfExpiresAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(expiresAt_)
        return *expiresAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Sessions::getExpiresAt() const noexcept
{
    return expiresAt_;
}
void Sessions::setExpiresAt(const ::trantor::Date &pExpiresAt) noexcept
{
    expiresAt_ = std::make_shared<::trantor::Date>(pExpiresAt);
    dirtyFlag_[13] = true;
}
void Sessions::setExpiresAtToNull() noexcept
{
    expiresAt_.reset();
    dirtyFlag_[13] = true;
}

void Sessions::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Sessions::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "verifier",
        "code_challenge",
        "code_challenge_method",
        "created_at",
        "access_token",
        "expires_in",
        "refresh_expires_in",
        "refresh_token",
        "token_type",
        "not_before_policy",
        "session_state",
        "scope",
        "expires_at"
    };
    return inCols;
}

void Sessions::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getVerifier())
        {
            binder << getValueOfVerifier();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getCodeChallenge())
        {
            binder << getValueOfCodeChallenge();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCodeChallengeMethod())
        {
            binder << getValueOfCodeChallengeMethod();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAccessToken())
        {
            binder << getValueOfAccessToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getExpiresIn())
        {
            binder << getValueOfExpiresIn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getRefreshExpiresIn())
        {
            binder << getValueOfRefreshExpiresIn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getRefreshToken())
        {
            binder << getValueOfRefreshToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getTokenType())
        {
            binder << getValueOfTokenType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getNotBeforePolicy())
        {
            binder << getValueOfNotBeforePolicy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getSessionState())
        {
            binder << getValueOfSessionState();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getScope())
        {
            binder << getValueOfScope();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getExpiresAt())
        {
            binder << getValueOfExpiresAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Sessions::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    return ret;
}

void Sessions::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getVerifier())
        {
            binder << getValueOfVerifier();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getCodeChallenge())
        {
            binder << getValueOfCodeChallenge();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCodeChallengeMethod())
        {
            binder << getValueOfCodeChallengeMethod();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAccessToken())
        {
            binder << getValueOfAccessToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getExpiresIn())
        {
            binder << getValueOfExpiresIn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getRefreshExpiresIn())
        {
            binder << getValueOfRefreshExpiresIn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getRefreshToken())
        {
            binder << getValueOfRefreshToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getTokenType())
        {
            binder << getValueOfTokenType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getNotBeforePolicy())
        {
            binder << getValueOfNotBeforePolicy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getSessionState())
        {
            binder << getValueOfSessionState();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getScope())
        {
            binder << getValueOfScope();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getExpiresAt())
        {
            binder << getValueOfExpiresAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Sessions::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getVerifier())
    {
        ret["verifier"]=getValueOfVerifier();
    }
    else
    {
        ret["verifier"]=Json::Value();
    }
    if(getCodeChallenge())
    {
        ret["code_challenge"]=getValueOfCodeChallenge();
    }
    else
    {
        ret["code_challenge"]=Json::Value();
    }
    if(getCodeChallengeMethod())
    {
        ret["code_challenge_method"]=getValueOfCodeChallengeMethod();
    }
    else
    {
        ret["code_challenge_method"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getAccessToken())
    {
        ret["access_token"]=getValueOfAccessToken();
    }
    else
    {
        ret["access_token"]=Json::Value();
    }
    if(getExpiresIn())
    {
        ret["expires_in"]=getValueOfExpiresIn();
    }
    else
    {
        ret["expires_in"]=Json::Value();
    }
    if(getRefreshExpiresIn())
    {
        ret["refresh_expires_in"]=getValueOfRefreshExpiresIn();
    }
    else
    {
        ret["refresh_expires_in"]=Json::Value();
    }
    if(getRefreshToken())
    {
        ret["refresh_token"]=getValueOfRefreshToken();
    }
    else
    {
        ret["refresh_token"]=Json::Value();
    }
    if(getTokenType())
    {
        ret["token_type"]=getValueOfTokenType();
    }
    else
    {
        ret["token_type"]=Json::Value();
    }
    if(getNotBeforePolicy())
    {
        ret["not_before_policy"]=getValueOfNotBeforePolicy();
    }
    else
    {
        ret["not_before_policy"]=Json::Value();
    }
    if(getSessionState())
    {
        ret["session_state"]=getValueOfSessionState();
    }
    else
    {
        ret["session_state"]=Json::Value();
    }
    if(getScope())
    {
        ret["scope"]=getValueOfScope();
    }
    else
    {
        ret["scope"]=Json::Value();
    }
    if(getExpiresAt())
    {
        ret["expires_at"]=getExpiresAt()->toDbStringLocal();
    }
    else
    {
        ret["expires_at"]=Json::Value();
    }
    return ret;
}

Json::Value Sessions::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 14)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getVerifier())
            {
                ret[pMasqueradingVector[1]]=getValueOfVerifier();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getCodeChallenge())
            {
                ret[pMasqueradingVector[2]]=getValueOfCodeChallenge();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getCodeChallengeMethod())
            {
                ret[pMasqueradingVector[3]]=getValueOfCodeChallengeMethod();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[4]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getAccessToken())
            {
                ret[pMasqueradingVector[5]]=getValueOfAccessToken();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getExpiresIn())
            {
                ret[pMasqueradingVector[6]]=getValueOfExpiresIn();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getRefreshExpiresIn())
            {
                ret[pMasqueradingVector[7]]=getValueOfRefreshExpiresIn();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getRefreshToken())
            {
                ret[pMasqueradingVector[8]]=getValueOfRefreshToken();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getTokenType())
            {
                ret[pMasqueradingVector[9]]=getValueOfTokenType();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getNotBeforePolicy())
            {
                ret[pMasqueradingVector[10]]=getValueOfNotBeforePolicy();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getSessionState())
            {
                ret[pMasqueradingVector[11]]=getValueOfSessionState();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getScope())
            {
                ret[pMasqueradingVector[12]]=getValueOfScope();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getExpiresAt())
            {
                ret[pMasqueradingVector[13]]=getExpiresAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getVerifier())
    {
        ret["verifier"]=getValueOfVerifier();
    }
    else
    {
        ret["verifier"]=Json::Value();
    }
    if(getCodeChallenge())
    {
        ret["code_challenge"]=getValueOfCodeChallenge();
    }
    else
    {
        ret["code_challenge"]=Json::Value();
    }
    if(getCodeChallengeMethod())
    {
        ret["code_challenge_method"]=getValueOfCodeChallengeMethod();
    }
    else
    {
        ret["code_challenge_method"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getAccessToken())
    {
        ret["access_token"]=getValueOfAccessToken();
    }
    else
    {
        ret["access_token"]=Json::Value();
    }
    if(getExpiresIn())
    {
        ret["expires_in"]=getValueOfExpiresIn();
    }
    else
    {
        ret["expires_in"]=Json::Value();
    }
    if(getRefreshExpiresIn())
    {
        ret["refresh_expires_in"]=getValueOfRefreshExpiresIn();
    }
    else
    {
        ret["refresh_expires_in"]=Json::Value();
    }
    if(getRefreshToken())
    {
        ret["refresh_token"]=getValueOfRefreshToken();
    }
    else
    {
        ret["refresh_token"]=Json::Value();
    }
    if(getTokenType())
    {
        ret["token_type"]=getValueOfTokenType();
    }
    else
    {
        ret["token_type"]=Json::Value();
    }
    if(getNotBeforePolicy())
    {
        ret["not_before_policy"]=getValueOfNotBeforePolicy();
    }
    else
    {
        ret["not_before_policy"]=Json::Value();
    }
    if(getSessionState())
    {
        ret["session_state"]=getValueOfSessionState();
    }
    else
    {
        ret["session_state"]=Json::Value();
    }
    if(getScope())
    {
        ret["scope"]=getValueOfScope();
    }
    else
    {
        ret["scope"]=Json::Value();
    }
    if(getExpiresAt())
    {
        ret["expires_at"]=getExpiresAt()->toDbStringLocal();
    }
    else
    {
        ret["expires_at"]=Json::Value();
    }
    return ret;
}

bool Sessions::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("verifier"))
    {
        if(!validJsonOfField(1, "verifier", pJson["verifier"], err, true))
            return false;
    }
    else
    {
        err="The verifier column cannot be null";
        return false;
    }
    if(pJson.isMember("code_challenge"))
    {
        if(!validJsonOfField(2, "code_challenge", pJson["code_challenge"], err, true))
            return false;
    }
    else
    {
        err="The code_challenge column cannot be null";
        return false;
    }
    if(pJson.isMember("code_challenge_method"))
    {
        if(!validJsonOfField(3, "code_challenge_method", pJson["code_challenge_method"], err, true))
            return false;
    }
    else
    {
        err="The code_challenge_method column cannot be null";
        return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(4, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("access_token"))
    {
        if(!validJsonOfField(5, "access_token", pJson["access_token"], err, true))
            return false;
    }
    if(pJson.isMember("expires_in"))
    {
        if(!validJsonOfField(6, "expires_in", pJson["expires_in"], err, true))
            return false;
    }
    if(pJson.isMember("refresh_expires_in"))
    {
        if(!validJsonOfField(7, "refresh_expires_in", pJson["refresh_expires_in"], err, true))
            return false;
    }
    if(pJson.isMember("refresh_token"))
    {
        if(!validJsonOfField(8, "refresh_token", pJson["refresh_token"], err, true))
            return false;
    }
    if(pJson.isMember("token_type"))
    {
        if(!validJsonOfField(9, "token_type", pJson["token_type"], err, true))
            return false;
    }
    if(pJson.isMember("not_before_policy"))
    {
        if(!validJsonOfField(10, "not_before_policy", pJson["not_before_policy"], err, true))
            return false;
    }
    if(pJson.isMember("session_state"))
    {
        if(!validJsonOfField(11, "session_state", pJson["session_state"], err, true))
            return false;
    }
    if(pJson.isMember("scope"))
    {
        if(!validJsonOfField(12, "scope", pJson["scope"], err, true))
            return false;
    }
    if(pJson.isMember("expires_at"))
    {
        if(!validJsonOfField(13, "expires_at", pJson["expires_at"], err, true))
            return false;
    }
    return true;
}
bool Sessions::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 14)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Sessions::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("verifier"))
    {
        if(!validJsonOfField(1, "verifier", pJson["verifier"], err, false))
            return false;
    }
    if(pJson.isMember("code_challenge"))
    {
        if(!validJsonOfField(2, "code_challenge", pJson["code_challenge"], err, false))
            return false;
    }
    if(pJson.isMember("code_challenge_method"))
    {
        if(!validJsonOfField(3, "code_challenge_method", pJson["code_challenge_method"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(4, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("access_token"))
    {
        if(!validJsonOfField(5, "access_token", pJson["access_token"], err, false))
            return false;
    }
    if(pJson.isMember("expires_in"))
    {
        if(!validJsonOfField(6, "expires_in", pJson["expires_in"], err, false))
            return false;
    }
    if(pJson.isMember("refresh_expires_in"))
    {
        if(!validJsonOfField(7, "refresh_expires_in", pJson["refresh_expires_in"], err, false))
            return false;
    }
    if(pJson.isMember("refresh_token"))
    {
        if(!validJsonOfField(8, "refresh_token", pJson["refresh_token"], err, false))
            return false;
    }
    if(pJson.isMember("token_type"))
    {
        if(!validJsonOfField(9, "token_type", pJson["token_type"], err, false))
            return false;
    }
    if(pJson.isMember("not_before_policy"))
    {
        if(!validJsonOfField(10, "not_before_policy", pJson["not_before_policy"], err, false))
            return false;
    }
    if(pJson.isMember("session_state"))
    {
        if(!validJsonOfField(11, "session_state", pJson["session_state"], err, false))
            return false;
    }
    if(pJson.isMember("scope"))
    {
        if(!validJsonOfField(12, "scope", pJson["scope"], err, false))
            return false;
    }
    if(pJson.isMember("expires_at"))
    {
        if(!validJsonOfField(13, "expires_at", pJson["expires_at"], err, false))
            return false;
    }
    return true;
}
bool Sessions::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 14)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Sessions::validJsonOfField(size_t index,
                                const std::string &fieldName,
                                const Json::Value &pJson,
                                std::string &err,
                                bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 128)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 128)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 128)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 128)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 32)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 32)";
                return false;
            }

            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 32)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 32)";
                return false;
            }

            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 128)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 128)";
                return false;
            }

            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
