apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-secret            # optional; defaults to metadata.name
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: oidc.keycloak.clientID
      remoteRef:
        key: system/keycloak/argocd
        property: client-id
    - secretKey: oidc.keycloak.clientSecret
      remoteRef:
        key: system/keycloak/argocd
        property: client-secret
    - secretKey: server.secretkey  
      remoteRef:
        key: system/argocd/server
        property: secret-key   
