apiVersion: batch/v1
kind: Job
metadata:
  name: create-keycloak-db
  namespace: {{ .Release.Namespace }}
  annotations:
    "argocd.argoproj.io/hook": "Sync"
    "argocd.argoproj.io/hook-delete-policy": "HookSucceeded"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: psql
          image: bitnami/postgresql:16
          command:
            - bash
            - -c
            - |
              echo "Waiting for PostgreSQL to be ready..."
              until pg_isready -h database-system-postgresql -U postgres; do
                sleep 2
              done

              echo "Creating user if needed..."
              psql -h database-system-postgresql -U postgres <<EOF
              DO \$\$
              DECLARE
                user_exists BOOLEAN;
              BEGIN
                SELECT EXISTS (SELECT FROM pg_catalog.pg_user WHERE usename = '${KEYCLOAK_DB_USERNAME}') INTO user_exists;
                IF NOT user_exists THEN
                  EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${KEYCLOAK_DB_USERNAME}', '${KEYCLOAK_DB_PASSWORD}');
                END IF;
              END
              \$\$;
              EOF

              echo "Checking if database exists and creating if needed..."
              db_exists=$(psql -h database-system-postgresql -U postgres -tAc "SELECT 1 FROM pg_database WHERE datname = 'keycloak'")
              if [ "$db_exists" != "1" ]; then
                echo "Creating database keycloak..."
                psql -h database-system-postgresql -U postgres -c "CREATE DATABASE keycloak OWNER \"$KEYCLOAK_DB_USERNAME\""
              else
                echo "Database keycloak already exists."
              fi
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-credentials
                  key: password
            - name: KEYCLOAK_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: password
            - name: KEYCLOAK_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: username
