apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-repo
  namespace: {{ .Release.Namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: 0h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-repo
    creationPolicy: Owner
  data:
    - secretKey: name
      remoteRef:
        key: system/argocd/github-repo
        property: name
    - secretKey: type
      remoteRef:
        key: system/argocd/github-repo
        property: type
    - secretKey: project
      remoteRef:
        key: system/argocd/github-repo
        property: project
    - secretKey: url
      remoteRef:
        key: system/argocd/github-repo
        property: url
    - secretKey: sshPrivateKey
      remoteRef:
        key: system/argocd/github-repo
        property: sshPrivateKey
  template:
    data:
      type: git
      name: Salonmaster
